// saga actions 정의
export const sagaActions = {
  FETCH_POSTS: 'POST/FETCH_POSTS',
  CREATE_POST: 'POST/CREATE_POST',
  UPDATE_POST: 'POST/UPDATE_POST',
  DELETE_POST: 'POST/DELETE_POST',
  RESET_FORM: 'POST/RESET_FORM'
};
